apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: woopick-backend
  labels:
    cloud.googleapis.com/location: europe-west3
spec:
  template:
    spec:
      serviceAccountName: $SA_CLOUDRUN_BACKEND
      containers:
      - image: europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_PORT
          value: "8080"
        - name: PROJECT_ID
          value: $PROJECT_ID
        - name: FIRESTORE_EMULATOR_HOST
          value: "localhost:8888"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: JWT_SECRET
  traffic:
  - percent: 100
    latestRevision: true
      
