version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: woo-backend
      POSTGRES_DB: integration-test
      POSTGRES_PASSWORD: woo-backend
    ports:
      - '5432:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d