version: '3.9'

services:
  firestore-emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=test-project
      - PORT=8888
    ports:
      - 8888:8888
  wiremock:
    image: wiremock/wiremock:3.1.0
    container_name: wiremock-container
    command: --verbose
    ports:
      - "1080:8080"
    volumes:
      - ${PWD}/__test__/wiremock:/home/wiremock
  application:
    image: hehe:latest
    ports:
      - 5000:5000
    environment:
      NODE_ENV: test
      SERVICE_PORT: 5000
      WOO_BASE_URL: http://wiremock:8080
      JWT_SECRET: secret
      FIRESTORE_EMULATOR_HOST: firestore-emulator:8888
      FIRESTORE_PROJECT_ID: test-project
      PROJECT_ID: test-project

    depends_on:
      firestore-emulator:
        condition: service_started
      wiremock:
        condition: service_started