version: "3.9"

services:
  application:
    image: $IMAGE_NAME
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      SERVICE_PORT: 8080
      WOO_BASE_URL: http://wiremock:8080
      JWT_SECRET: secret
      FIRESTORE_EMULATOR_HOST: 127.0.0.1:8888