version: "3.9"

services:
  application:
    image: test-image:latest
    depends_on:
      gcloud-spanner-run-up:
        condition: service_completed_successfully
    ports:
      - 3000:3000
    environment:
      SERVICE_PORT: 3000
      SPANNER_EMULATOR_HOST: spanner-emulator:9010
      SPANNER_PROJECT_ID: test-project
      SPANNER_INSTANCE_ID: test-instance
      SPANNER_DATABASE_ID: woo-app-users
      WOO_BASE_URL: http://wiremock:8080
      JWT_SECRET: secret
