services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test-database
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  wiremock:
    image: wiremock/wiremock:3.1.0
    container_name: wiremock-container
    command: --verbose
    ports:
      - "1080:8080"
    volumes:
      - ${PWD}/__test__/wiremock:/home/wiremock

  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      NODE_ENV: test
      WHERE: local
      SERVICE_PORT: 5003
      WOO_BASE_URL: http://wiremock:8080
      JWT_SECRET: secret
      PROJECT_ID: test-project
      MONGO_INITDB_DATABASE: test-database
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      PRODUCTS_IMAGES_BUCKET: test-bucket
      MONGO_USERS_DATABASE: users

    depends_on:
      mongodb:
        condition: service_started # Waits for MongoDB to pass its health check
      wiremock:
        condition: service_started
