version: "3.9"

services:
  application:
    image: $IMAGE_NAME
    depends_on:
      wiremock:
        condition: service_completed_successfully
    ports:
      - 8080:8080
    environment:
      SERVICE_PORT: 8080
      WOO_BASE_URL: http://wiremock:8080
      JWT_SECRET: secret