version: "3.9"

services:
  firestore-emulator:
    image: fixl/firebase-emulator-suite:12.7
    ports:
      - "8888:8888"
    environment:
      - FIREBASE_PROJECT_ID=test-project
      - FIRESTORE=true
      - FIRESTORE_PORT=8888
      - AUTH=false
  wiremock:
    image: wiremock/wiremock:3.1.0
    container_name: wiremock-container
    command: --verbose
    ports:
      - "1080:8080"
    volumes:
      - ${PWD}/__test__/wiremock:/home/wiremock
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    environment:
      NODE_ENV: test
      SERVICE_PORT: 5003
      WOO_BASE_URL: http://wiremock:8080
      JWT_SECRET: secret
      FIRESTORE_EMULATOR_HOST: firestore-emulator:8888
      FIRESTORE_PROJECT_ID: test-project
      PROJECT_ID: test-project
      PRODUCTS_IMAGES_BUCKET: test-bucket
    depends_on:
      firestore-emulator:
        condition: service_started
      wiremock:
        condition: service_started
