version: '3.8'

services:
  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator:1.5.4
    ports:
      - 9010:9010
      - 9020:9020
  
  gcloud-spanner-run-up:
    depends_on:
      spanner-emulator:
        condition: service_started
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    volumes:
      - type: bind
        source: ./scripts/run_up_spanner.sh
        target: /scripts/run_up_spanner.sh
    command: |
      bash -c 'source /scripts/run_up_spanner.sh'

  wiremock:
    image: wiremock/wiremock:3.1.0
    command: --verbose
    ports:
      - "1080:8080"
    volumes:
      - ${PWD}/integration-test/wiremock:/home/wiremock