version: "3.9"

services:
  application:
    image: hehe:latest
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
      PROJECT_ID: test-project
      SERVICE_PORT: 5000
      WOO_BASE_URL: http://wiremock:8080
      JWT_SECRET: secret
      FIRESTORE_EMULATOR_HOST: host.docker.internal:8888
      FIRESTORE_PORT: 8888