version: "3.9"

services:
  application:
    image: europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:latest
    ports:
      - 5000:5000
    environment:
      NODE_ENV: test
      SERVICE_PORT: 5000
      PROJECT_ID: test-project
      WOO_BASE_URL: http://wiremock:8080
      JWT_SECRET: secret
      FIRESTORE_EMULATOR_HOST: host.docker.internal:8888