version: '3.8'

services:

  wiremock:
    image: wiremock/wiremock:3.1.0
    command: --verbose
    ports:
      - "1080:8080"
    volumes:
      - ${PWD}/__test__/wiremock:/home/wiremock
  
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      SERVICE_PORT: 8080
      WOO_BASE_URL: http://wiremock:8080
      JWT_SECRET: secret
    depends_on:
      - wiremock