version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: woo-backend
      POSTGRES_DB: integration-test
      POSTGRES_PASSWORD: woo-backend
    ports:
      - '5432:5432'
    volumes:
      - ./migrations/create:/docker-entrypoint-initdb.d/create
      - ./migrations/insert:/docker-entrypoint-initdb.d/insert
  
  wiremock:
    image: wiremock/wiremock:3.1.0
    command: --verbose
    ports:
      - "1080:8080"
    volumes:
      - ${PWD}/integration-test/wiremock:/home/wiremock

  application:
    ports:
      - 3000:3000
    environment:
      SERVICE_PORT : 3000
      DB_HOST : localhost
      DB_USER : woo-backend
      DB_PASSWORD : woo-backend
      DB_NAME : integration-test
      DB_PORT : 5432
      WOO_BASE_URL : http://localhost:1080
      JWT_SECRET : secret