version: '3.9'

services:
  application:
    image: europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:latest
    ports:
      - 5000:5000
    environment:
      NODE_ENV: test
      SERVICE_PORT: 5000
      PROJECT_ID: test-project
      WOO_BASE_URL: http://wiremock:8080
      JWT_SECRET: secret
      FIRESTORE_EMULATOR_HOST: host.docker.internal:8888

  wiremock:
    image: wiremock/wiremock:3.1.0
    command: --verbose
    ports:
      - "1080:8080"
    volumes:
      - ${PWD}/__test__/wiremock:/home/wiremock