version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: woo-backend
      POSTGRES_DB: integration-test
      POSTGRES_PASSWORD: woo-backend
    ports:
      - '5432:5432'
    volumes:
      - ./migrations/create:/docker-entrypoint-initdb.d
      - ./migrations/insert:/docker-entrypoint-initdb.d

  wiremock:
    image: wiremock/wiremock:3.1.0
    command: --verbose
    ports:
      - "1080:8080"
    volumes:
      - ${PWD}/integration-test/wiremock:/home/wiremock