export const PRODUCT_PER_PAGE = 100;
export const CATEGORIES_PER_PAGE = 100;
export const ORDERS_PER_PAGE = 100;
export const ROOT_CATEGORY_PARENT_ID = 0;
export const FIRESTORE_ALLOWED_BATCH_SIZE = 500;
export const MONGO_ALLOWED_BATCH_SIZE = 1000;
export const WOO_MAX_BATCH_SIZE = 100;
export const CHUNKS_MAX_BATCH_SIZE_400 = 400;