name: Build Image and Check for Tests

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:

  check-test:
    name: Execute integrations test
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3

        - name: Execute integration tests
          run: |-
            npm install -g firebase-tools
            npm install --force
            firebase emulators:exec --project=test-project 'npm run test:firestore'
