name: Build Image and Check for Tests

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Woo-Pick-Fullfillment-Inventory/Backend-Woo-Inventory
          token: ${{ secrets.WOOPICK_GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker build --platform linux/amd64 -t woopick-backend:latest .

  check-test:
    name: Execute Test Cases
    needs:
      - build-push-gcr
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install

      - name: Start wiremock and application
        run: |-
          docker-compose -f docker-compose.github-pipeline.yml up -d

      - name: Run all the tests
        run: npm run test

      - name: Check Docker container logs
        if: always()
        run: docker-compose -f docker-compose.github-pipeline.yml logs

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.github-pipeline.yml down
