name: Build Image and Check for Tests

on:
  push:
    branches:
      - "**"
      - "!main"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: woopick-backend

jobs:
  check-test:
    name: Execute Test Cases
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Start wiremock, firestore-emulator and application
        run: |-
          docker-compose -f docker-compose.local-test.yml up -d --build

      - name: Check Docker Network
        run: docker network ls

      - name: Check Wiremock Mount
        run: docker exec wiremock-container ls -al /home/wiremock/mappings

      - name: Run all the tests
        run: npm run test

      - name: Check Docker container logs
        if: always()
        run: docker-compose -f docker-compose.github-pipeline.yml logs

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.github-pipeline.yml down
