name: Build Image and Check for Tests

on:
  push:
    branches:
      - "**"
      - "!main"
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: woopick-backend

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Run Docker Linter
        run: npm run lint-docker

      - name: Run Markdown Linter
        run: npm run lint-markdown

      - name: Run Typescript Linter
        run: npm run lint

      - name: Run Npm Build
        run: npm run build

  build-push-gcr:
    name: Build and push to GCR
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Woo-Pick-Fullfillment-Inventory/Backend-Woo-Inventory
          token: ${{ secrets.WOOPICK_GITHUB_TOKEN }}

      - name: Authenticate to WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SA_GH_ACTIONS }}
          token_format: access_token
          export_environment_variables: true

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./auto_update_tag.sh -v patch

      - name: Build and push Docker image
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet
          docker build --platform linux/amd64 -t europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:latest .
          docker build --platform linux/amd64 -t europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:$GIT_TAG .
          docker push europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:latest
          docker push europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:$GIT_TAG

  check-test:
    name: Execute Test Cases
    needs:
      - build-push-gcr
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SA_GH_ACTIONS }}
          token_format: access_token
          export_environment_variables: true
      
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install

      - name: Replace Docker image
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet
          sed -i 's#\$IMAGE_NAME#europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:latest#g' 'docker-compose.github-pipeline.yml'

      - name: Start wiremock and application
        run: |-
          docker-compose -f docker-compose.yml -f docker-compose.github-pipeline.yml up -d

      - name: Run all the tests
        run: firebase emulators:exec --project=test-project 'npm run test'

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml -f docker-compose.github-pipeline.yml down
