name: Build Image and Check for Tests

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  emulator_test:
    name: Run all tests using Firebase Emulator Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: npm install
      - name: Run all the tests
        run: firebase emulators:exec --project=test-project 'npm run test'