name: Check out code

on:
  push:
    branches:
      - "**"
      - "!main"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: woopick-backend

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: npm install

      - name: Run Docker Linter
        run: npm run lint-docker

      - name: Run Markdown Linter
        run: npm run lint-markdown

      - name: Run Typescript Linter
        run: npm run lint

      - name: Run Npm Build
        run: npm run build

      - name: Run Prettier
        run: npm run prettier-check

  run-tests:
    name: Execute Test Cases
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: npm install

      - name: Start wiremock, firestore-emulator and application
        run: |-
          docker-compose -f docker-compose.github-pipeline.yml up -d --build

      - name: Check Docker Network
        run: docker network ls

      - name: Check Wiremock Mount
        run: docker exec wiremock-container ls -al /home/wiremock/mappings

      - name: Run all the tests
        run: npm run test-pipeline

      - name: Check Docker container logs
        if: always()
        run: docker-compose -f docker-compose.github-pipeline.yml logs

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.github-pipeline.yml down
