name: Check out code

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/checkout@v3

      - name: install dependencies
        run: npm install

      - name: Run Docker Linter
        run: npm run lint-docker

      - name: Run Markdown Linter
        run: npm run lint-markdown

      - name: Run Typescript Linter
        run: npm run lint

      - name: Run Npm Build
        run: npm run build

  run-tests:
    name: Execute Test Cases
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - uses: actions/checkout@v3

      - name: install dependencies
        run: npm install
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-username: admin
          mongodb-password: pass
          mongodb-db: test-database

      - name: Start wiremock and application
        run: |-
          docker-compose -f docker-compose.github-pipeline.yml up -d --build

      - name: Run all the tests
        run: echo "TODO  Run all the tests"

      - name: Check Docker container logs
        if: always()
        run: docker-compose -f docker-compose.github-pipeline.yml logs

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.github-pipeline.yml down
