on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: woopick-backend
  REGION: europe-west3
  DEPLOYMENT_NAME: woopick-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read  
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SA_GH_ACTIONS }}
          token_format: access_token
          export_environment_variables: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy woopick-backend \
            --image europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:latest \
            --service-account ${{ secrets.SA_GH_ACTIONS }} \
            --platform managed \
            --region europe-west3 \
            --allow-unauthenticated
