on:
  push:
    branches:
      - '**'
      - '!main'

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: woopick-backend
  REGION: europe-west3
  DEPLOYMENT_NAME: woopick-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read  
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SA_GH_ACTIONS }}
          token_format: access_token
          export_environment_variables: true

      - name: Prepare and Deploy to Cloud Run
        run: |
          sed -i "s|\$PROJECT_ID|$PROJECT_ID|g" cloudrun_deployment.yml
          sed -i "s|\$IMAGE_NAME|$IMAGE_NAME|g" cloudrun_deployment.yml
          sed -i "s|\$PORT_PLACEHOLDER|${{ secrets.PORT }}|g" cloudrun_deployment.yml
          sed -i "s|\$SPANNER_PROJECT_ID|$PROJECT_ID|g" cloudrun_deployment.yml
          sed -i "s|\$SPANNER_INSTANCE_ID|${{ secrets.SPANNER_INSTANCE_ID }}|g" cloudrun_deployment.yml
          sed -i "s|\$SPANNER_DATABASE_ID|${{ secrets.SPANNER_DATABASE_ID }}|g" cloudrun_deployment.yml
          sed -i "s|\$SA_GH_ACTIONS|${{ secrets.SA_GH_ACTIONS }}|g" cloudrun_deployment.yml

          gcloud run services replace cloudrun_deployment.yml
