on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SPANNER_PROJECT_ID: ${{ secrets.SPANNER_PROJECT_ID }}
  SPANNER_INSTANCE_ID: ${{ secrets.SPANNER_INSTANCE_ID }}
  SPANNER_DATABASE_ID: ${{ secrets.SPANNER_DATABASE_ID }}
  CLOUDRUN_SA: ${{ secrets.SA_CLOUDRUN_BACKEND }}
  GITHUB_SA: ${{ secrets.SA_GH_ACTIONS }}
  WIP: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER  }}
  IMAGE_NAME: woopick-backend


jobs:
  deploy-to-cloudrun:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read  
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: $WIP
          service_account: $GITHUB_SA
          token_format: access_token
          export_environment_variables: true

      - name: Prepare and Deploy to Cloud Run
        run: |
          sed -i "s|\$PROJECT_ID|$PROJECT_ID|g" cloudrun_deployment.yml
          sed -i "s|\$IMAGE_NAME|$IMAGE_NAME|g" cloudrun_deployment.yml
          sed -i "s|\$SPANNER_PROJECT_ID|$PROJECT_ID|g" cloudrun_deployment.yml
          sed -i "s|\$SPANNER_INSTANCE_ID|$SPANNER_INSTANCE_ID|g" cloudrun_deployment.yml
          sed -i "s|\$SPANNER_DATABASE_ID|$SPANNER_DATABASE_ID|g" cloudrun_deployment.yml
          sed -i "s|\$SA_CLOUDRUN_BACKEND|$secrets.SA_CLOUDRUN_BACKEND|g" cloudrun_deployment.yml

          gcloud run services replace cloudrun_deployment.yml
