name: Check, build and deploy

on:
  push:
    branches:
      - '**'

jobs:
  checks:
    runs-on: ubuntu-latest
    name: integration-test
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Run Integration Tests
        run: npm run test