name: Build and deploy

on:
  push:
  
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: woopick-backend
  REGION: europe-west3
  DEPLOYMENT_NAME: woopick-backend

jobs:
  build-push-gcr:
    name: Build and push to GCR
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read  

    outputs:
      image-name: ${{ steps.output-image-name.outputs.image-name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Woo-Pick-Fullfillment-Inventory/Backend-Woo-Inventory
          token: ${{ secrets.WOOPICK_GITHUB_TOKEN}}

      - name: Authenticate to WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SA_GH_ACTIONS }}
          token_format: access_token
          export_environment_variables: true
    
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/auto_update_tag.sh -v patch

      - name: Build and push Docker image
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet
          docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:latest .
          docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:$GIT_TAG .
          docker push europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:latest
          docker push europe-west3-docker.pkg.dev/$PROJECT_ID/woopick-registry/$IMAGE_NAME:$GIT_TAG

      - name: Prepare and Deploy to Cloud Run
        run: |
          sed -i "s|\$PROJECT_ID|$PROJECT_ID|g" cloudrun_deployment.yml
          sed -i "s|\$IMAGE_NAME|$IMAGE_NAME|g" cloudrun_deployment.yml
          sed -i "s|\$SPANNER_PROJECT_ID|$PROJECT_ID|g" cloudrun_deployment.yml
          sed -i "s|\$SPANNER_INSTANCE_ID|${{ secrets.SPANNER_INSTANCE_ID }}|g" cloudrun_deployment.yml
          sed -i "s|\$SPANNER_DATABASE_ID|${{ secrets.SPANNER_DATABASE_ID }}|g" cloudrun_deployment.yml
          sed -i "s|\$SA_CLOUDRUN_BACKEND|${{ secrets.SA_CLOUDRUN_BACKEND }}|g" cloudrun_deployment.yml

          gcloud run services replace cloudrun_deployment.yml